export const PurpleOS = {
    Colors: {
        PURPLEOS_BG: 0x0f0c1b,
        PURPLEOS_PRIMARY: 0x7c3aed,
        PURPLEOS_SUCCESS: 0x10b981,
        PURPLEOS_DANGER: 0xef4444,
        PURPLEOS_WARN: 0xf59e0b,
    },
    Icons: {
        LOCK: '🔒',
        UNLOCK: '🔓',
        EYE: '👁️',
        CROWN: '👑',
        GEAR: '⚙️',
        PENCIL: '✏️',
        USERS: '👥',
        SHIELD: '🛡️',
        ZAP: '⚡',
        INFO: 'ℹ️',
        NOTE: '📝',
        TRASH: '🗑️',
        ACTIVITY: '🎮',
        HIDE: '👁️‍🗨️',
        LOOP: '🔄',
        KICK: '🚫',
        ALLOW: '✅',
        DENY: '❌',
        TEMPLATE: '📋',
        CHANNEL: '🔊',
        CLOCK: '⏱️',
        AUTONAME: '🏷️',
        CHECK: '▸',
        BULLET: '›',
        SPARKLE: '✦',
        DOT: '•',
    },
    Helpers: {
        sectionHeader: (name) => `\n**— ${name.toUpperCase()} —**\n`,
        label: (name) => `**${name}:**`,
        dotSeparate: (...items) => items.filter(Boolean).join(' • '),
        smallHint: (text) => `\`💡\` *${text}*`,
    },
    Text: {
        PANEL_TITLE: 'Room Control Center',
        PANEL_SUBTITLE: 'OS-grade controls for your voice room.',
        COOLDOWN: 'Slow down • Try again in {s}s.',
        APPLIED: 'Applied.',
        SYNCED: 'Synced.',
        ACCESS_DENIED: 'Access denied.',
        POLICY_BLOCKED: 'Policy blocked.',
    }
};
