export const SafeLimits = {
    MAX_TEMPLATE_NAME_LEN: 32,
    MAX_ROOM_NAME_LEN: 100,
    MAX_IMPORT_BYTES: 102_400,
    MAX_EMPTY_DELETE_SECONDS: 3600,
    MAX_COOLDOWN_SECONDS: 3600,
    MAX_ROOMS_PER_USER: 10,
    MAX_ALLOW_DENY_ENTRIES: 50,
    JOIN_LEAVE_EVENTS_CAP: 50,
    GUILD_CREATE_WINDOW_MS: 10_000,
    GUILD_CREATE_MAX: 20,
    IMPORT_CONFIRM_TTL_MS: 300_000,
    MAX_PENDING_IMPORTS: 200,
    MAX_IMPORTED_LOBBIES: 100,
    MAX_ACTIVITY_TAG_LEN: 100,
    MAX_NAME_TEMPLATE_LEN: 100,
    MIN_EMPTY_DELETE_SECONDS: 5,
    MIN_ROOMS_PER_USER: 1,
    MIN_USER_LIMIT: 0,
    MAX_USER_LIMIT: 99,
    MAX_ROOM_NOTE_LEN: 120,
};

export const SNOWFLAKE_REGEX = /^\d{17,20}$/;
